version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports: 
      - "49181:2181"
      - "22"
  nimbus:
    build:
      context: ./storm-nimbus
      dockerfile: Dockerfile
    ports:
      - "49773:3773"
      - "49772:3772"
      - "49627:6627"
      - "22"
    links: 
      - zookeeper:zk
  supervisor:
    build:
        context: ./storm-supervisor
        dockerfile: Dockerfile
    ports:
      - "8000"
      - "22"
    links: 
      - nimbus:nimbus
      - zookeeper:zk
  ui:
    build:
        context: ./storm-ui
        dockerfile: Dockerfile
    ports:
      - "49080:8080"
      - "22"
    links: 
      - nimbus:nimbus
      - zookeeper:zk
  mongodb:
    build: ./mongodb
    ports:
      - "27017"

